---
- name: "Playing with Ansible and Git"
  hosts: all
  connection: local
  become: "yes"

  tasks:
  ## Create filesystems
  - name: Create filesystems
    block:
      - name: Create FAT32 filesystem in boot partition
        filesystem:
          dev: '{{ install_drive }}1'
          fstype: fat
          opts: '-F 32 -n EFI'
          force: yes
      - name: Create ext4 filesystem in root volume
        filesystem:
          dev: '{{ install_drive }}2'
          fstype: ext4
          force: yes
      - name: Create filesystem in swap volume
        filesystem:
          dev: '{{ install_drive }}3'
          fstype: swap
          force: yes