---
- name: "Playing with Ansible and Git"
  hosts: all
  connection: local
  become: "yes"

  tasks:
  ## Mount filesystems
  - name: Mount filesystems
    block:
      # root
      - name: Mount root filesystem
        mount:
          path: /mnt
          src: '{{ install_drive }}2'
          fstype: ext4
          state: mounted
      # mountpoint
      - name: Create mountpoint for {boot} volume
        file:
          path: /mnt/boot
          state: directory
        file:
          path: /mnt/boot/efi
          state: directory
      # boot
      - name: Mount boot filesystem
        mount:
          path: /mnt/boot/efi
          src: '{{ install_drive }}1'
          fstype: fat
          state: mounted
      # swap
      - name: Mount swap filesystem
        command: 'swapon {{ install_drive }}3'