---
- name: "Playing with Ansible and Git"
  hosts: all
  connection: local
  become: "yes"

  tasks:
  ## Pacstrap
  - name: Run pacstrap
    command: pacstrap /mnt base base-devel linux-lts linux-firmware ansible git bash-completion networkmanager wireless_tools modemmanager mobile-broadband-provider-info usb_modeswitch rp-pppoe network-manager-applet net-tools wpa_supplicant dialog neovim curl wget tar alacritty grub efibootmgr

  - name: Generate blank fstab
    command: genfstab -U /mnt >> /mnt/etc/fstab

  - name: Enter arch-chroot
    command: arch-chroot /mnt ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
    command: arch-chroot /mnt hwclock --systohc --utc
    command: arch-chroot /mnt bootctl install
    command: arch-chroot /mnt "default arch" > /boot/efi/loader/loader.conf
    command: arch-chroot /mnt "title  Arch Linux" > /boot/efi/loader/entries/arch.conf
    command: arch-chroot /mnt "linux  /vmlinuz-linux-lts" >> /boot/efi/loader/entries/arch.conf
    command: arch-chroot /mnt "options  root=/dev/sdc2 rw" >> /boot/efi/loader/entries/arch.conf