---
- name: Setup grub
  block:
    - name: Install grub
      command: arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
    - name: Create grub config
      command: arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg