---
- name: Clone arch
  when: user_password == user_password_check
  block:
    - name: Clone settings
      command: mkdir {{ arch_dir }}
      command: git clone https://github.com/azchatlanin/arch.git {{ arch_dir }}

    - name: Make my directory tree readable
      file:
        path: {{ arch_dir }}
        mode: u=rwX,g=rX,o=rX
        recurse: yes