---
- name: Run pacstrap
  when: user_password == user_password_check
  block:
    - name: Enter arch-chroot localtime
      command: arch-chroot /mnt ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime

    - name: Enter arch-chroot hwclock
      command: arch-chroot /mnt hwclock --systohc --utc

