---
- name: Setup hostname
  when: user_password == user_password_check
  block:
    - name: Set hostname
      copy:
        content: 'arch'
        dest: /mnt/etc/hostname

    - name: Set localhost
      copy:
        content: |
          127.0.0.1 localhost arch
          ::1 localhost arch
        dest: /mnt/etc/hosts
