---
- name: Setup locales
  when: user_password == user_password_check
  block:
    - name: Configure locale.gen
      lineinfile:
        dest: /mnt/etc/locale.gen
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - {regex: en_US\.UTF-8 UTF-8, line: en_US.UTF-8 UTF-8}
        - {regex: ru_RU\.UTF-8 UTF-8, line: ru_RU.UTF-8 UTF-8}

    - name: Create locale.conf
      copy:
        content: "LANG=en_US.UTF-8"
        dest: /mnt/etc/locale.conf

    - name: Generate locales
      command: arch-chroot /mnt export LANG=en_US.UTF-8
      command: arch-chroot /mnt locale-gen