---
- name: Setup user account
  when: user_password == user_password_check
  block:
    - name: Change root password
      expect:
        command: arch-chroot /mnt passwd
        responses:
          (?i)password: "{{ user_password }}"

    - name: Create user account
      command: arch-chroot /mnt useradd --create-home --user-group --groups wheel {{ user_name }} --password {{ user_password | password_hash('sha512') }}

    - name: Give passwordless sudo access to wheel group
      copy:
        content: '%wheel ALL=(ALL) ALL'
        dest: /mnt/etc/sudoers.d/wheel
        validate: /usr/sbin/visudo --check --file=%s