---
- hosts: localhost
  connection: local
  vars:
    install_drive: /dev/sdc

  vars_prompt:
    - name: "user_real_name"
      prompt: "Enter your full real name (user_real_name)"
      private: false
    - name: "user_name"
      prompt: "Enter your system user name (user_name)"
      private: false
    - name: "user_password"
      prompt: "Enter your user password (user_password)"
      private: false
    - name: "user_password_check"
      prompt: "Repeat your user password (user_password_check)"
      private: false
    - name: "start_partition"
      prompt: "Start partition (yes/No)"
      private: false
    - name: "format_filesystem"
      prompt: "Start format filesystem (yes/No)"
      private: false

  roles:
    - arch
