---
- hosts: localhost
  connection: local
  vars:
    install_drive: /dev/nvme0n1p

  vars_prompt:
    - name: "user_name"
      prompt: "Enter your system user name:"
      private: false
    - name: "user_password"
      prompt: "Enter your user password one:"
      private: false
    - name: "user_password_check"
      prompt: "Enter your user password two:"
      private: false
    - name: "start_partition"
      prompt: "Start partition (yes/No)"
      private: false
    - name: "format_filesystem"
      prompt: "Start format filesystem (yes/No)"
      private: false

  roles:
    - role: arch
